apiVersion: v1
kind: ServiceAccount
metadata:
  name: amana-vault-auth
  namespace: default
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: amana-vault
  namespace: default
spec:
  provider:
    vault:
      server: https://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: amana
          serviceAccountRef:
            name: amana-vault-auth
            audiences:
              - vault
